#![no_main]
//! Fuzz target for `ColumnDecoder::decode` and `ColumnDecoder::decode_bytes`.
//!
//! Feeds arbitrary bytes into the unified column decoder to exercise all
//! codec paths (Chimp, Gorilla, delta-of-delta, dictionary, bitmap, plain,
//! RLE, nullable wrappers).  Any panic or memory-safety violation is a bug.

use libfuzzer_sys::fuzz_target;

use chronix_encoding::{ColumnDecoder, DecodedColumn, EncodedBlock, EncodingType};

fuzz_target!(|data: &[u8]| {
    // 1. Try `decode_bytes` on raw input.
    let _ = ColumnDecoder::decode_bytes(data);

    // 2. Try `decode` with each encoding variant so every codec path gets
    //    exercised regardless of what discriminant the raw bytes would map to.
    //
    //    `EncodingType::ALL` is generated by the same macro that declares the
    //    enum, so this list cannot fall behind the codec list. A hand-written
    //    array here used to be the risk: omitting a codec from it left that
    //    decoder unfuzzed, and nothing anywhere would say so.
    for &enc in EncodingType::ALL {
        let block = EncodedBlock {
            encoding: enc,
            payload: data.to_vec(),
        };
        let _ = ColumnDecoder::decode(&block);
    }
});
